# Generated by Django 3.2.11 on 2022-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fleetmodel',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
